export const REQUEST_GUIDES = 'REQUEST_GUIDES';
export const RECEIVE_GUIDES = 'RECEIVE_GUIDES';
export const SELECT_GUIDEPATH = 'SELECT_GUIDEPATH';
export const INVALIDATE_GUIDEPATH = 'INVALIDATE_GUIDEPATH';

export const GET_BREADCRUMBS = 'GET_BREADCRUMBS';