export const REQUEST_GUIDES = 'REQUEST_GUIDES';
export const RECEIVE_GUIDES = 'RECEIVE_GUIDES';
export const SELECT_GUIDEPATH = 'SELECT_GUIDEPATH';
export const INVALIDATE_GUIDEPATH = 'INVALIDATE_GUIDEPATH';

export const GET_BREADCRUMBS = 'GET_BREADCRUMBS';

export const ADD_DIRECTORY_REQUEST = 'ADD_DIRECTORY_REQUEST';
export const ADD_DIRECTORY_SUCCESS = 'ADD_DIRECTORY_SUCCESS';
export const ADD_DIRECTORY_ERROR = 'ADD_DIRECTORY_ERROR';

export const ADD_ALERT = 'ADD_ALERT';
export const UPDATE_ALERT = 'UPDATE_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SAVE_MARKDOWN_REQUEST = 'SAVE_MARKDOWN_REQUEST';
export const SAVE_MARKDOWN_SUCCESS = 'SAVE_MARKDOWN_SUCCESS';
export const SAVE_MARKDOWN_ERROR = 'SAVE_MARKDOWN_ERROR';
